# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining source code
COPY . .

# Compile the TypeScript code
RUN npm install -g typescript
RUN npm run build

# Set the environment variable
ENV NODE_ENV production

# Expose the default Node.js port
EXPOSE 3000

# Command to run the application
CMD [ "npm", "start" ]
